### ISSUE TITLE
ImportError: No module named capi

### ISSUE THREAD

**Issue by joudinet** [arend/py80211#3]
Hi,
I've compiled libnl-3.2.27 with python wrapper but I get the following error message when I try example04.py:

```
$ python example04.py wlan1
Traceback (most recent call last):
  File "example04.py", line 1, in <module>
    from py80211.station import *
  File "/home/johan/py80211-master/build/lib.linux-x86_64-2.7/py80211/station.py", line 25, in <module>
    import netlink.genl.capi as genl
ImportError: No module named capi
```

In libnl-3.2.27's python directory, I have netlink.capi and netlink.genl._capi, but no netlink.genl.capi:

```
tree build/lib.linux-x86_64-2.7/
build/lib.linux-x86_64-2.7/
└── netlink
    ├── capi.py
    ├── capi.pyc
    ├── _capi.so
    ├── core.py
    ├── core.pyc
    ├── genl
    │   ├── _capi.so
    │   ├── __init__.py
    │   └── __init__.pyc
    ├── __init__.py
    ├── __init__.pyc
    ├── route
    │   ├── address.py
    │   ├── _capi.so
    │   ├── __init__.py
    │   ├── link.py
    │   ├── links
    │   │   ├── dummy.py
    │   │   ├── inet.py
    │   │   ├── __init__.py
    │   │   └── vlan.py
    │   ├── qdisc
    │   │   ├── htb.py
    │   │   └── __init__.py
    │   └── tc.py
    └── util.py
```

**Comment by arend** [comment]
Will try it over here. Last couple of times I only build Python wrappers of libnl and not full lib. Not sure if that could explain this issue though. Will get back to you.

**Comment by arend** [comment]
For me it seems to work:
creating build/lib.linux-x86_64-2.7/netlink/genl
copying ./netlink/genl/capi.py -> build/lib.linux-x86_64-2.7/netlink/genl
copying ./netlink/genl/__init__.py -> build/lib.linux-x86_64-2.7/netlink/genl
So can you provide output of 'python setup.py build' command.
